name=CanDccBooster
version=1.0.0
author=Bruno
sentence=Bibliothèque Discovery 2026 pour booster DRV8874 avec RailCom HF.
paragraph=Gère le DCC, le cutout, la télémétrie et le RailCom pour boosters DRV8874.
category=Communication
architectures=esp32
